export const ADD_PRODUCT_TO_CART = 'addProductToCart'
export const ADD_PRODUCT_TO_CART_WITH_QT = 'addProductToCartWithQt'
export const ADD_PRODUCTS_TO_CART_FROM_PORTAL = 'addProductsToCartFromPortal'
export const REDUCE_PRODUCT_TO_CART = 'reduceProductToCart'
export const REMOVE_PRODUCT_TO_CART = 'removeProductToCart'
export const CLEAN_ALL_CART = 'cleanAllCart'